import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/Header";
import { AuthProvider } from "@/contexts/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "hw3",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`min-h-screen bg-background flex-1 flex flex-col relative font-sans antialiased ${inter.className}`}>
            <AuthProvider>

                <Header />
                <main className="flex-1">
                    {children}
                </main>
            </AuthProvider>
        </body>
        </html>
    );
}
